[package]
name = "sql_unlocker"
version = "0.1.1"
edition = "2021"
authors = ["mcnbc12@gmail.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colour = "0.6.0"
oracle_lib = { path = "../oracle_lib" }
