[package]
name = "oracle_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oracle = "0.5.5"
rust-embed = "6.4.0"
tempfile = "3.3.0"